/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: likesenape (https://sketchfab.com/likesenape)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceman-model-4494aa9be0c84b9dbef590a588b493cf
Title: Spaceman Model
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/scene.gltf');
  const { actions } = useAnimations(animations, group);
  const mixer = useRef();



  const speed = 0.5;

  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime();
    group.current.position.x = Math.sin(time * speed) * 2; 
    group.current.position.y += delta * 0.05;
    group.current.position.z -= delta * 0.02;
    group.current.rotation.x += delta * 0.2;
    group.current.rotation.y += delta * 0.1;

    if (mixer.current) mixer.current.update(delta);
  });

  return (
    <group ref={group} {...props} scale={[1.5, 1.5, 1.5]} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Sphere007">
              <mesh
                name="Sphere007_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere007_0.geometry}
                material={materials.Root}
              />
            </group>
            <group
              name="NurbsPath004"
              position={[0.632, 0.09, 4.163]}
              rotation={[-0.526, -0.213, -1.309]}
              scale={0.355}
            >
              <mesh
                name="NurbsPath004_0"
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath004_0.geometry}
                material={materials['tuta_metallico.001']}
              />
            </group>
            <group
              name="Plane005"
              position={[0.099, 2.147, 3.085]}
              rotation={[1.593, -0.01, 0.019]}
              scale={[0.786, 1.012, 1.012]}
            >
              <mesh
                name="Plane005_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane005_0.geometry}
                material={materials.tuta_metallico}
              />
            </group>
            <group
              name="Cylinder002"
              position={[0.113, 1.496, 3.313]}
              rotation={[0.022, -0.019, -0.01]}
              scale={0.867}
            >
              <mesh
                name="Cylinder002_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002_0.geometry}
                material={materials.tuta_metallico}
              />
            </group>
            <group name="Plane006">
              <mesh
                name="Plane006_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane006_0.geometry}
                material={materials.Root}
              />
            </group>
            <group
              name="Sphere008"
              position={[0.108, 1.44, 3.194]}
              rotation={[0.022, -0.019, -0.01]}
              scale={0.918}
            >
              <mesh
                name="Sphere008_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere008_0.geometry}
                material={materials.tuta_metallico}
              />
              <mesh
                name="Sphere008_1"
                castShadow
                receiveShadow
                geometry={nodes.Sphere008_1.geometry}
                material={materials.specchio}
              />
            </group>
            <group name="Sphere009">
              <mesh
                name="Sphere009_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_0.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere009_0_1"
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_0_1.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere009_0_2"
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_0_2.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere009_0_3"
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_0_3.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere009_0_4"
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_0_4.geometry}
                material={materials['Material.001']}
              />
            </group>
            <group name="Empty" position={[0.048, 1.382, 4.313]} scale={9.823}>
              <group
                name="Spot005"
                position={[0.343, -1.563, -0.005]}
                rotation={[1.592, 0.184, -1.15]}
                scale={0.102}
              >
                <group name="Spot005_1" />
              </group>
              <group
                name="Sun002"
                position={[0.507, 0.554, 3.164]}
                rotation={[-0.171, 0.128, -0.32]}
                scale={0.102}
              >
                <group name="Sun002_1" />
              </group>
              <group
                name="Spot009"
                position={[0.9, 0.536, 0.569]}
                rotation={[-0.628, 0.798, 0.968]}
                scale={0.102}
              >
                <group name="Spot009_1" />
              </group>
              <group
                name="Spot008"
                position={[-1.025, -0.622, 0.423]}
                rotation={[0.488, -0.649, -2.185]}
                scale={0.102}
              >
                <group name="Spot008_1" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');